apiVersion: apps/v1
kind: Deployment
metadata:
  name: quizapp
  namespace: quizapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quizapp
  template:
    metadata:
      labels:
        app: quizapp
    spec:
      serviceAccountName: external-secrets-sa
      containers:
      - name: quizapp
        image: 266735817823.dkr.ecr.eu-west-2.amazonaws.com/quiz-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: quizapp-db-secrets
              key: host
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: quizapp-db-secrets
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: quizapp-db-secrets
              key: password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: quizapp-db-secrets
              key: database

