apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: quizapp-secretstore
  namespace: quizapp
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-west-2
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: secrets

--- 

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: quizapp-db-secrets
  namespace: quizapp
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: quizapp-secretstore
    kind: SecretStore
  target:
    name: quizapp-db-secrets
    creationPolicy: Owner
  data:
    - secretKey: db_host
      remoteRef:
        key: quizapp/database3
        property: host
    - secretKey: db_user
      remoteRef:
        key: quizapp/database3
        property: user
    - secretKey: db_password
      remoteRef:
        key: quizapp/database3
        property: password
    - secretKey: db_name
      remoteRef:
        key: quizapp/database3
        property: database
