apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cert-issuer
spec:
  acme:
    email: "hamzahsahal9@gmail.com"
    server: "https://acme-v02.api.letsencrypt.org/directory"
    privateKeySecretRef:
      name: issuer
    solvers:
      - dns01:
          route53:
            hostedZoneID: ${var.hosted_zone_id}
        selector:
          dnsZones:
            - "eks.hamzahsahal.com" 
      - http01:
          ingress:
            class: nginx


    